//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace awesome_exam.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrderDataView
    {
        public string FullName { get; set; }
        public string email { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string Title { get; set; }
    }
}
